name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.31
        env:
          DB_CONNECTION: mysql
          DB_HOST: localhost
          DB_PORT: 3306
          DB_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_USER: root

        ports:
          - 3306:3306
        options: --name=database --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t api .
        
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
         
      - name: Run tests
        run: docker run api vendor/bin/phpunit
        env:
          DB_HOST: localhost
