name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.31
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t api .

      - name: Copy env variables
          run: cp .env.test .env

      - name: Run migration
        run: docker run api vendor/bin/phpunit
        env:
          DB_CONNECTION: mysql
          DB_USERNAME: tms
          DB_DATABASE: test
